version: '3.8'

services:
 app:
    build:
      context: .
    environment:
      APP_NAME: Bandit
      APP_PORT: 4000
      APP_SECRET: koPmu7TJCwD8mttV9vgWUeU7iuu/zTPOR3sX4UalM9KkYEVGPfyi0PeTVzu1TT8C
      APP_HOST: localhost
      APP_HTTP_SCHEMA: http
      DB_USERNAME: root
      DB_PASSWORD: D1q9f0C2&PEW
      DB_HOSTNAME: db
      DB_DATABASE: bandit
      DB_PORT: 5432
      DB_SSL: null
      DB_CA_CERTFILE_PATH: null
    restart: unless-stopped
    command: sh -c "/app/bin/migrate && /app/bin/server"
    ports:
      - '4000:4000'
    depends_on:
      - db
 db:
    image: postgres:15.6
    environment:
      POSTGRES_DB: bandit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: D1q9f0C2&PEW
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  app:
    driver: local
