version: '3.8'

services:
  app1:
    image: clivern/lynx:0.12.0
    environment:
      APP_NAME: Lynx
      APP_PORT: 4001
      APP_SECRET: koPmu7TJCwD8mttV9vgWUeU7iuu/zTPOR3sX4UalM9KkYEVGPfyi0PeTVzu1TT8C
      APP_HOST: localhost
      APP_HTTP_SCHEMA: http
      DB_USERNAME: root
      DB_PASSWORD: D1q9f0C2&PEW
      DB_HOSTNAME: db
      DB_DATABASE: lynx
      DB_PORT: 5432
      DB_SSL: null
      DB_CA_CERTFILE_PATH: null
      MIX_ENV: prod
    command: sh -c "/app/bin/migrate && /app/bin/server"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4001/_health"]
      interval: 30s
      retries: 3
    restart: unless-stopped
    depends_on:
      - db

  app2:
    image: clivern/lynx:0.12.0
    environment:
      APP_NAME: Lynx
      APP_PORT: 4002
      APP_SECRET: koPmu7TJCwD8mttV9vgWUeU7iuu/zTPOR3sX4UalM9KkYEVGPfyi0PeTVzu1TT8C
      APP_HOST: localhost
      APP_HTTP_SCHEMA: http
      DB_USERNAME: root
      DB_PASSWORD: D1q9f0C2&PEW
      DB_HOSTNAME: db
      DB_DATABASE: lynx
      DB_PORT: 5432
      DB_SSL: null
      DB_CA_CERTFILE_PATH: null
      MIX_ENV: prod
    command: sh -c "/app/bin/migrate && /app/bin/server"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4002/_health"]
      interval: 30s
      retries: 3
    restart: unless-stopped
    depends_on:
      - db

  app3:
    image: clivern/lynx:0.12.0
    environment:
      APP_NAME: Lynx
      APP_PORT: 4003
      APP_SECRET: koPmu7TJCwD8mttV9vgWUeU7iuu/zTPOR3sX4UalM9KkYEVGPfyi0PeTVzu1TT8C
      APP_HOST: localhost
      APP_HTTP_SCHEMA: http
      DB_USERNAME: root
      DB_PASSWORD: D1q9f0C2&PEW
      DB_HOSTNAME: db
      DB_DATABASE: lynx
      DB_PORT: 5432
      DB_SSL: null
      DB_CA_CERTFILE_PATH: null
      MIX_ENV: prod
    command: sh -c "/app/bin/migrate && /app/bin/server"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4003/_health"]
      interval: 30s
      retries: 3
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: lynx
      POSTGRES_USER: root
      POSTGRES_PASSWORD: D1q9f0C2&PEW
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25.4-alpine3.18
    ports:
      - '80:80'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/_health"]
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx

volumes:
  db:
    driver: local
  nginx_logs:
    driver: local
