version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      APP_NAME: Lynx
      APP_PORT: 4000
      APP_SECRET: koPmu7TJCwD8mttV9vgWUeU7iuu/zTPOR3sX4UalM9KkYEVGPfyi0PeTVzu1TT8C
      APP_HOST: localhost
      APP_HTTP_SCHEMA: http
      DB_USERNAME: root
      DB_PASSWORD: D1q9f0C2&PEW
      DB_HOSTNAME: db
      DB_DATABASE: lynx
      DB_PORT: 5432
      DB_SSL: null
      DB_CA_CERTFILE_PATH: null
      MIX_ENV: prod
    command: sh -c "/app/bin/migrate && /app/bin/server"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: lynx
      POSTGRES_USER: root
      POSTGRES_PASSWORD: D1q9f0C2&PEW
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25.4-alpine3.18
    ports:
      - '80:80'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/_ready"]
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db:
    driver: local
  app:
    driver: local
